### ISSUE TITLE
Publish please :)

### ISSUE THREAD

**Issue by Voltir** [DavidGregory084/schemes#5]
I'd really like to use para :)

**Comment by DavidGregory084** [comment]
Sorry @Voltir! I've been neglecting my duties :cry: 

0.2.0 is on its way now.

If you're interested I'd be very pleased to make you a maintainer?

I'll spend some time tomorrow setting up automatic publishing in any case.

**Comment by DavidGregory084** [comment]
0.2.0 is on Central now 🙂
